--- #YAML:1.0
name:               BZ-Client
version:            1.04
abstract:           BZ::Client - A client for the Bugzilla web services API.
author:
    - Jochen Wiedmann <jochen.wiedmann@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    URI:          0
    XML::Parser:  0
    XML::Writer:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
